
"""auto

Revision ID: 2b1ecfb37e8c
Revises: caf09c1cab7a
Create Date: 2025-12-10 13:09:45.926715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '2b1ecfb37e8c'
down_revision: Union[str, Sequence[str], None] = 'caf09c1cab7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('matrix', sa.ARRAY(sa.Integer(), dimensions=2), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maps')
    # ### end Alembic commands ###
