
"""Add is_verified to users

Revision ID: caf09c1cab7a
Revises: 03d9c906a3ae
Create Date: 2025-12-09 14:06:31.552343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'caf09c1cab7a'
down_revision: Union[str, Sequence[str], None] = '03d9c906a3ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
