"""update friends and friend_requests relationships

Revision ID: 05177c89c50f
Revises: 9c2665c1ec11
Create Date: 2025-11-17 15:13:25.520249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05177c89c50f'
down_revision: Union[str, Sequence[str], None] = '9c2665c1ec11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
