"""Initial revision

Revision ID: b687896de460
Revises: c4c15f719d4e
Create Date: 2025-11-17 12:54:33.096395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b687896de460'
down_revision: Union[str, Sequence[str], None] = 'c4c15f719d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username_from', sa.String(), nullable=False),
    sa.Column('username_to', sa.String(), nullable=False),
    sa.Column('send_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['username_from'], ['users.username'], ),
    sa.ForeignKeyConstraint(['username_to'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friend_requests')
    # ### end Alembic commands ###
