"""Create friend_requests table

Revision ID: d6fc04804c8f
Revises: cf613468486c
Create Date: 2025-11-17 14:46:37.403983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6fc04804c8f'
down_revision: Union[str, Sequence[str], None] = 'cf613468486c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('friend_requests', sa.Column('from_user_id', sa.Integer(), nullable=False))
    op.add_column('friend_requests', sa.Column('to_user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'friend_requests', 'users', ['to_user_id'], ['id'])
    op.create_foreign_key(None, 'friend_requests', 'users', ['from_user_id'], ['id'])
    op.drop_column('friend_requests', 'username_to')
    op.drop_column('friend_requests', 'username_from')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friend_requests', sa.Column('username_from', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('friend_requests', sa.Column('username_to', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'friend_requests', type_='foreignkey')
    op.drop_constraint(None, 'friend_requests', type_='foreignkey')
    op.drop_column('friend_requests', 'to_user_id')
    op.drop_column('friend_requests', 'from_user_id')
    op.drop_table('friends')
    # ### end Alembic commands ###
