"""Add CASCADE to friend_requests and friends foreign keys

Revision ID: e9502b333fb6
Revises: 0a69290acc29
Create Date: 2025-11-17 17:07:37.463824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9502b333fb6'
down_revision: Union[str, Sequence[str], None] = '0a69290acc29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('friend_requests_to_user_id_fkey'), 'friend_requests', type_='foreignkey')
    op.drop_constraint(op.f('friend_requests_from_user_id_fkey'), 'friend_requests', type_='foreignkey')
    op.create_foreign_key(None, 'friend_requests', 'users', ['to_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'friend_requests', 'users', ['from_user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('friends_user_id_fkey'), 'friends', type_='foreignkey')
    op.drop_constraint(op.f('friends_friend_id_fkey'), 'friends', type_='foreignkey')
    op.create_foreign_key(None, 'friends', 'users', ['friend_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'friends', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'friends', type_='foreignkey')
    op.drop_constraint(None, 'friends', type_='foreignkey')
    op.create_foreign_key(op.f('friends_friend_id_fkey'), 'friends', 'users', ['friend_id'], ['id'])
    op.create_foreign_key(op.f('friends_user_id_fkey'), 'friends', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'friend_requests', type_='foreignkey')
    op.drop_constraint(None, 'friend_requests', type_='foreignkey')
    op.create_foreign_key(op.f('friend_requests_from_user_id_fkey'), 'friend_requests', 'users', ['from_user_id'], ['id'])
    op.create_foreign_key(op.f('friend_requests_to_user_id_fkey'), 'friend_requests', 'users', ['to_user_id'], ['id'])
    # ### end Alembic commands ###
